#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_PHP_FILES=`git diff --cached --name-only --diff-filter=ACMR HEAD|grep \\\\.php$`  

echo "Starting Ethereum precommit..."

echo "$PROJECT"
exit 1

if ["$STAGED_PHP_FILES" != ""]; then
  echo "Linting PHP code..."
  for FILE in $STAGED_PHP_FILES; do
    php -l -d display_errors=0 "$PROJECT/$FILE"

    if [ $? != 0 ]; then
      echo "Fix the error(s) before commit."
      exit 1
    fi

    FILES="$FILES $FILE"
  done
fi

